# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Victor\PyQt_Apps\Image Converter\PyQt-Apps\Voice_Password_App\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(508, 406)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 491, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(140, 0, 20, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(340, 0, 3, 61))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(50, 50, 411, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 80, 351, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.email.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid black;\n"
"color:black;\n"
"padding-bottom: 7px")
        self.email.setText("")
        self.email.setObjectName("email")
        self.verticalLayout.addWidget(self.email)
        self.username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.username.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid black;\n"
"color:black;\n"
"padding-bottom: 7px")
        self.username.setText("")
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password.setEnabled(True)
        self.password.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid black;\n"
"color:black;\n"
"padding-bottom: 7px")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.nextButton = QtWidgets.QPushButton(Form)
        self.nextButton.setGeometry(QtCore.QRect(130, 300, 241, 41))
        self.nextButton.setStyleSheet("QPushButton {border-radius: 14px;\n"
"color: white;\n"
"background-color: rgb(0, 0, 13);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"font: 10pt \"Arial\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 25); \n"
"color: rgb(0, 153, 255);\n"
"font-weight: bold;\n"
"}\n"
"")
        self.nextButton.setObjectName("nextButton")
        self.rememberMe = QtWidgets.QCheckBox(Form)
        self.rememberMe.setGeometry(QtCore.QRect(200, 350, 111, 20))
        self.rememberMe.setObjectName("rememberMe")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Login"))
        self.email.setPlaceholderText(_translate("Form", "Email"))
        self.username.setPlaceholderText(_translate("Form", "Username"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.nextButton.setText(_translate("Form", "Login"))
        self.rememberMe.setText(_translate("Form", "Remember Me"))
