# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Victor\PyQt_Apps\Image Converter\PyQt-Apps\Voice_Password_App\Recording.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(507, 407)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 481, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLabel(Form)
        self.password.setGeometry(QtCore.QRect(50, 120, 401, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(40)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgba(64, 64, 64, 19);")
        self.password.setText("")
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.startRecordingButton = QtWidgets.QPushButton(Form)
        self.startRecordingButton.setGeometry(QtCore.QRect(90, 230, 321, 61))
        self.startRecordingButton.setStyleSheet("QPushButton {border-radius: 14px;\n"
"color: white;\n"
"background-color: rgb(0, 0, 13);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"font: 10pt \"Arial\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 25); \n"
"color: rgb(0, 153, 255);\n"
"font-weight: bold;\n"
"}\n"
"")
        self.startRecordingButton.setObjectName("startRecordingButton")
        self.stopRecordingButton = QtWidgets.QPushButton(Form)
        self.stopRecordingButton.setGeometry(QtCore.QRect(90, 310, 321, 61))
        self.stopRecordingButton.setStyleSheet("QPushButton {border-radius: 14px;\n"
"color: white;\n"
"background-color: rgb(51, 51, 51);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"font: 10pt \"Arial\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(64, 64, 64); \n"
"color: rgb(0, 153, 255);\n"
"font-weight: bold;\n"
"}\n"
"")
        self.stopRecordingButton.setObjectName("stopRecordingButton")
        self.listening_label = QtWidgets.QLabel(Form)
        self.listening_label.setGeometry(QtCore.QRect(70, 200, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listening_label.setFont(font)
        self.listening_label.setText("")
        self.listening_label.setAlignment(QtCore.Qt.AlignCenter)
        self.listening_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.listening_label.setObjectName("listening_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "You will be using a voice password, click start recording and say the word you will like to use as a password. Click stop recording to stop the recording. (Please note that your password should be at least 8 letters long)"))
        self.startRecordingButton.setText(_translate("Form", "Start Recording "))
        self.stopRecordingButton.setText(_translate("Form", "Stop Recording"))
